local map = vim.keymap.set
local community = require("community")

map({ "n", "i" }, "<C-s>", "<cmd>w<cr>", { desc = "Save file", silent = true })
map("n", "<leader>w", "<cmd>w<cr>", { desc = "Save file", silent = true })
map("n", "<leader>q", "<cmd>confirm q<cr>", { desc = "Quit window", silent = true })
map("n", "<leader>Q", "<cmd>qa<cr>", { desc = "Quit all", silent = true })
map("n", "<leader>x", "<cmd>bd<cr>", { desc = "Close buffer", silent = true })
map("n", "<Tab>", "<cmd>bnext<cr>", { desc = "Next buffer", silent = true })
map("n", "<S-Tab>", "<cmd>bprevious<cr>", { desc = "Previous buffer", silent = true })
map("n", "<C-o>", "<C-o>", { desc = "Jump back", silent = true })
map("n", "<C-i>", "<C-i>", { desc = "Jump forward", silent = true })
map("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search", silent = true })

map("n", "<leader>e", community.toggle_tree, { desc = "Toggle explorer", silent = true })
map("n", "<leader>o", community.focus_tree, { desc = "Focus explorer", silent = true })

map("n", "<leader>ff", community.find_files, { desc = "Find files", silent = true })
map("n", "<leader>fg", community.live_grep, { desc = "Live grep", silent = true })
map("n", "<leader>fb", community.buffers, { desc = "Buffers", silent = true })
map("n", "<leader>fr", community.recent, { desc = "Recent files", silent = true })
map("n", "<leader>fp", community.project_switcher, { desc = "Projects", silent = true })
map("n", "<leader>fh", community.help_tags, { desc = "Help tags", silent = true })
map("n", "<leader>?", community.keymaps, { desc = "Keymaps", silent = true })
map("n", "<leader>ch", "<cmd>WhichKey <leader><cr>", { desc = "Cheatsheet", silent = true })

map("n", "<leader>tt", "<cmd>ToggleTerm<cr>", { desc = "Terminal", silent = true })
map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics", silent = true })
map("n", "<leader>xw", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", { desc = "Buffer diagnostics", silent = true })
map("n", "<leader>xl", "<cmd>Trouble loclist toggle<cr>", { desc = "Location list", silent = true })
map("n", "<leader>xq", "<cmd>Trouble quickfix toggle<cr>", { desc = "Quickfix list", silent = true })

map("n", "<leader>gg", community.lazygit, { desc = "LazyGit", silent = true })
map("n", "<leader>gs", community.lazygit, { desc = "LazyGit", silent = true })
map("n", "<leader>gd", community.diffview_open, { desc = "Git diff", silent = true })
map("n", "<leader>gD", community.diffview_close, { desc = "Close diffview", silent = true })
map("n", "<leader>gb", community.toggle_blame, { desc = "Git blame", silent = true })
map("n", "<leader>gf", community.git_files, { desc = "Git files", silent = true })
map("n", "<leader>gB", community.git_branches, { desc = "Git branches", silent = true })
map("n", "<leader>gS", community.git_status, { desc = "Git status", silent = true })

map("n", "<leader>=", function()
  vim.lsp.buf.format({ async = true })
end, { desc = "Format buffer", silent = true })

map("n", "<C-h>", "<C-w>h", { desc = "Window left", silent = true })
map("n", "<C-j>", "<C-w>j", { desc = "Window down", silent = true })
map("n", "<C-k>", "<C-w>k", { desc = "Window up", silent = true })
map("n", "<C-l>", "<C-w>l", { desc = "Window right", silent = true })
