local map = vim.keymap.set
local opts = { silent = true }
local search = require("config.search")

map({ "n", "i" }, "<C-s>", "<cmd>w<cr>", { desc = "Save file", silent = true })
map("n", "<leader>w", "<cmd>w<cr>", { desc = "Save file", silent = true })
map("n", "<leader>q", "<cmd>confirm q<cr>", { desc = "Quit window", silent = true })
map("n", "<leader>Q", "<cmd>qa<cr>", { desc = "Quit all", silent = true })
map("n", "<leader>x", "<cmd>bd<cr>", { desc = "Close buffer", silent = true })
map("n", "<leader>e", search.explorer, { desc = "Explorer", silent = true })
map("n", "<leader>ff", search.files, { desc = "Find files", silent = true })
map("n", "<C-p>", search.files, { desc = "Find files", silent = true })
map("n", "<leader>fd", search.dirs, { desc = "Find directories", silent = true })
map("n", "<leader>fr", search.recent, { desc = "Recent files", silent = true })
map("n", "<leader>fg", search.grep, { desc = "Live grep", silent = true })
map("n", "<leader>fb", search.buffers, { desc = "Buffers", silent = true })
map("n", "<leader>fh", search.help, { desc = "Help tags", silent = true })
map("n", "<leader>fs", search.buffer_search, { desc = "Search buffer", silent = true })
map("n", "<leader>tt", "<cmd>ToggleTerm<cr>", { desc = "Toggle terminal", silent = true })
map("n", "<leader>bn", "<cmd>bnext<cr>", { desc = "Next buffer", silent = true })
map("n", "<leader>bp", "<cmd>bprevious<cr>", { desc = "Previous buffer", silent = true })
map("n", "<leader>/", search.buffer_search, { desc = "Search in file", silent = true })
map("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search", silent = true })
map("n", "<leader>?", search.keymaps, { desc = "Search keymaps", silent = true })
map("n", "<leader>=", "<cmd>lua vim.lsp.buf.format({ async = true })<cr>", { desc = "Format buffer", silent = true })

map("n", "<C-h>", "<C-w>h", opts)
map("n", "<C-j>", "<C-w>j", opts)
map("n", "<C-k>", "<C-w>k", opts)
map("n", "<C-l>", "<C-w>l", opts)
