local map = vim.keymap.set
local opts = { silent = true }
local search = require("config.search")

map({ "n", "i" }, "<C-s>", "<cmd>w<cr>", { desc = "Save file", silent = true })
map("n", "<leader>w", "<cmd>w<cr>", { desc = "Save file", silent = true })
map("n", "<leader>q", "<cmd>confirm q<cr>", { desc = "Quit window", silent = true })
map("n", "<leader>Q", "<cmd>qa<cr>", { desc = "Quit all", silent = true })
map("n", "<leader>x", "<cmd>bd<cr>", { desc = "Close buffer", silent = true })
map("n", "<leader>e", search.explorer, { desc = "Explorer", silent = true })
map("n", "<leader>ff", search.files, { desc = "Find files", silent = true })
map("n", "<C-p>", search.files, { desc = "Find files", silent = true })
map("n", "<leader>fd", search.dirs, { desc = "Find directories", silent = true })
map("n", "<leader>fr", search.recent, { desc = "Recent files", silent = true })
map("n", "<leader>fg", search.grep, { desc = "Live grep", silent = true })
map("n", "<leader>fb", search.buffers, { desc = "Buffers", silent = true })
map("n", "<leader>fh", search.help, { desc = "Help tags", silent = true })
map("n", "<leader>fs", search.buffer_search, { desc = "Search buffer", silent = true })
map("n", "<leader>tt", "<cmd>ToggleTerm<cr>", { desc = "Toggle terminal", silent = true })
map("n", "<leader>bn", "<cmd>bnext<cr>", { desc = "Next buffer", silent = true })
map("n", "<leader>bp", "<cmd>bprevious<cr>", { desc = "Previous buffer", silent = true })
map("n", "<leader>/", search.buffer_search, { desc = "Search in file", silent = true })
map("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search", silent = true })
map("n", "<leader>?", search.keymaps, { desc = "Search keymaps", silent = true })
map("n", "<leader>=", "<cmd>lua vim.lsp.buf.format({ async = true })<cr>", { desc = "Format buffer", silent = true })
map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", { desc = "Diagnostics", silent = true })
map("n", "<leader>xw", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", { desc = "Buffer diagnostics", silent = true })
map("n", "<leader>xl", "<cmd>Trouble loclist toggle<cr>", { desc = "Location list", silent = true })
map("n", "<leader>xq", "<cmd>Trouble quickfix toggle<cr>", { desc = "Quickfix list", silent = true })
map("n", "<leader>gg", search.git_status, { desc = "Git", silent = true })
map("n", "<leader>gs", search.git_status, { desc = "Git status", silent = true })
map("n", "<leader>gf", search.git_files, { desc = "Git files", silent = true })
map("n", "<leader>gB", search.git_branches, { desc = "Git branches", silent = true })
map("n", "<leader>gd", search.diffview_open, { desc = "Git diff", silent = true })
map("n", "<leader>gD", "<cmd>DiffviewClose<cr>", { desc = "Close diffview", silent = true })
map("n", "<leader>gb", search.toggle_blame, { desc = "Toggle git blame", silent = true })
map("n", "<leader>ss", function()
  require("persistence").save()
end, { desc = "Save session", silent = true })
map("n", "<leader>sl", function()
  require("persistence").load({ last = true })
end, { desc = "Restore last session", silent = true })
map("n", "<leader>sd", function()
  require("persistence").load()
end, { desc = "Restore dir session", silent = true })

map("n", "<C-h>", "<C-w>h", opts)
map("n", "<C-j>", "<C-w>j", opts)
map("n", "<C-k>", "<C-w>k", opts)
map("n", "<C-l>", "<C-w>l", opts)
